########################################################################
## Travis CI config for LimeSuite
##
## * not all components will be configured
## * the matrix builds Release and Debug
## * for linux + gcc, and osx + clang
########################################################################

sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

env:
  global:
    - INSTALL_PREFIX=/usr/local
    - SOAPY_SDR_BRANCH=master
    - BUILD_TYPE=Release

# whitelist
branches:
  only:
    - master
    - stable

before_install:

  # update after package changes
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

  # install development dependencies
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libusb-1.0-0-dev cmake libwxbase3.0-dev libwxgtk3.0-dev;fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list libusb || brew install libusb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list wxmac || brew install wxmac ; fi

install:

  # install SoapySDR from source
  - git clone https://github.com/pothosware/SoapySDR.git
  - pushd SoapySDR
  - git checkout ${SOAPY_SDR_BRANCH}
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make && sudo make install
  - popd

script:
  - mkdir temp && cd temp
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_EVB7COM=ON
  - make -j2
  - sudo make install
